# Generated by Django 4.2.7 on 2026-04-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_catalog',
                'ordering': ['sn'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='student_passports/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('home_address', models.TextField()),
                ('phone_no', models.CharField(max_length=20)),
                ('alt_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_graduation', models.CharField(blank=True, max_length=4, null=True)),
                ('graduation_class', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_of_training', models.CharField(blank=True, max_length=20, null=True)),
                ('student_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('it_student', 'IT Student'), ('nysc', 'NYSC')], default='full_time', max_length=20)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='management.coursecatalog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
