# Generated by Django 4.2.7 on 2026-07-15 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial_management_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_certificates', to='management.coursecatalog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_certificates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_certificates',
                'ordering': ['-issued_at'],
                'unique_together': {('recipient_name', 'course')},
            },
        ),
    ]
