# Generated by Django 4.2.7 on 2026-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_manualcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcertificate',
            name='grade',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('lower_credit', 'Lower Credit'), ('upper_credit', 'Upper Credit'), ('distinction', 'Distinction')], max_length=20),
        ),
    ]
