# Generated by Django 4.2.7 on 2026-09-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0003_manualcertificate_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiwesLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("course_of_study", models.CharField(max_length=200)),
                ("registration_no", models.CharField(max_length=50)),
                ("institution", models.CharField(max_length=200)),
                ("institution_state", models.CharField(max_length=100)),
                ("duration_months", models.PositiveSmallIntegerField(default=3)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("start_year", models.PositiveSmallIntegerField()),
                ("letter_date", models.DateField()),
                ("reference_id", models.CharField(max_length=50, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siwes_letters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "siwes_letters",
                "ordering": ["-issued_at"],
            },
        ),
    ]
