# Generated by Django 4.2.7 on 2026-09-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_siwesletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="siwesletter",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siwesletter",
            name="emailed_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
