# Generated by Django 4.2.7 on 2026-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_siwesletter_emailed_at_siwesletter_emailed_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualcertificate",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcertificate",
            name="emailed_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
